#!/usr/bin/env ruby
require 'thor'

require "docker_pid"

module DockerPid
  class CLI < Thor
    include Thor::Actions

    desc "container PID", "find container id from PID"
    option :verbose, type: :boolean, default: false, aliases: "-v"
    def container(pid)
      container_id = DockerPid::Host.docker_container_id(pid)
      info = DockerPid.container_info(container_id)
      
      info[:pid] = pid.to_i
      info[:container_id] = info[:container_id][0..11]
      keys = [:pid, :container_id, :name, :image, :ip]
      values = keys.zip(keys.map{|k| info[k]})
      print_table values, truncate: true
    rescue DockerPid::ProcessNotExist => e
      say("[Error] Process does not exist. (#{e})", Color::RED)
    rescue DockerPid::NotDockerProcess => e
      say("[Error] Process is not in docker container. (#{e})", Color::RED)
    end

    desc "gpuprocesses", "listing processes using gpu"
    option :verbose, type: :boolean, default: false, aliases: "-v"
    def gpuprocesses()
      procs = NvidiaSmi.processes
      values = []
      values<< ['PID', 'Process', 'Container ID', 'Container Name', 'Total GPU Mem(MB)', 'Num GPU']
      procs.map{|p| p.pid }.uniq.each do |pid|
        pgroup = procs.select{|p| p.pid == pid }
        proc_name = pgroup.first.name[0...24]
        gpu_mem = pgroup.map{|p| p.memory}.inject(0, :+)
        num_gpu = pgroup.size
        begin
          cid = DockerPid::Host.docker_container_id(pid)
          info = DockerPid.container_info(cid)
          values << [pid, proc_name, cid[0..11], info[:name], gpu_mem, num_gpu]
        rescue DockerPid::NotDockerProcess => e
          values << [pid, proc_name,'-', '-', gpu_mem, num_gpu]
        end
      end
      print_table values, truncate: true


    end
  end
end

DockerPid::CLI.start(ARGV)
